create table students
(
    student_id             INTEGER
        primary key,
    student_name           TEXT not null,
    module                 TEXT not null
        references modules (module_id),
    average_score          REAL,
    assessments_completed  INTEGER,
    performance_trend      REAL,
    max_consecutive_misses INTEGER,
    progress_in_semester   FLOAT
);

INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1000, 'Ben Murphy', 'CS210', 50.69, 2, -10.8, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1001, 'Darragh Ryan', 'CS210', 33.7, 2, -12.93, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1002, 'Abdula Ryan', 'CS210', 36.85, 2, 5.96, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1003, 'Ben Moran', 'CS210', 67.68, 3, -15.61, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1004, 'Ciara Byrne', 'CS210', 67.63, 3, -10.07, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1005, 'Michael McMahon', 'CS210', 56.8, 3, 18.45, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1006, 'Alex Smith', 'CS210', 46.31, 2, -3.5, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1007, 'Ben Kennedy', 'CS210', 77.04, 3, -23.9, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1008, 'Adam Smith', 'CS210', 53.05, 3, 7.71, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1009, 'Alex Sheehan', 'CS210', 44.36, 3, 15.79, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1010, 'Kate Byrne', 'CS210', 75.05, 3, 6.31, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1011, 'Ciara Doyle', 'CS210', 63.39, 3, 28.65, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1012, 'Leo Walsh', 'CS210', 36.24, 2, 17.75, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1013, 'Killian Murphy', 'CS210', 58.84, 3, -10.84, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1014, 'Adam Quinn', 'CS210', 57.21, 3, 19, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1015, 'Abdula McCarthy', 'CS210', 62.53, 3, 15.46, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1016, 'Conor McCarthy', 'CS210', 33.56, 2, 13.19, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1017, 'Aaliyah Sheehan', 'CS210', 59.63, 3, 9.49, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1018, 'Alex Boyle', 'CS210', 60.37, 3, 12.98, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1019, 'Conor Smith', 'CS210', 72.25, 3, -3.15, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1020, 'Megan McMahon', 'CS210', 49.45, 2, -16.68, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1021, 'Killian Byrne', 'CS210', 73.74, 3, 6.71, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1022, 'Alex Kelly', 'CS210', 59.3, 3, 19.1, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1023, 'Aaron Byrne', 'CS210', 52.06, 3, 4.49, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1024, 'Ben Murphy', 'CS210', 64.57, 3, -4.3, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1025, 'Aaron McCarthy', 'CS210', 61.4, 3, 19.86, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1026, 'Abdula Quinn', 'CS210', 55.82, 3, 22.85, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1027, 'Alex Doyle', 'CS210', 35.29, 2, -10.45, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1028, 'Michael Boyle', 'CS210', 71.32, 3, -3.85, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1029, 'Killian Moran', 'CS210', 68.79, 3, 13.19, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1030, 'Conor Murphy', 'CS210', 54.07, 3, 8.55, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1031, 'Aaliyah Smith', 'CS210', 59.09, 3, -45.29, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1032, 'Leo Kelly', 'CS210', 32.49, 2, 18.38, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1033, 'Kate Quinn', 'CS210', 78.6, 3, 12.46, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1034, 'Megan Murphy', 'CS210', 72.39, 3, -16.79, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1035, 'Kate McCarthy', 'CS210', 64.74, 3, 9.92, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1036, 'Alex Doyle', 'CS210', 27.91, 2, -1.08, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1037, 'Killian Moran', 'CS210', 45.92, 2, 9.54, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1038, 'Michael Murphy', 'CS210', 76.37, 3, 25.27, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1039, 'Adam Murphy', 'CS210', 47.78, 2, -11.41, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1040, 'Aaron Kennedy', 'CS210', 57.51, 3, -3.88, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1041, 'Aaron Sheehan', 'CS210', 71.1, 3, -14.76, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1042, 'Leo McMahon', 'CS210', 41.35, 2, 28.59, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1043, 'Conor Moran', 'CS210', 62.9, 3, 6.57, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1044, 'Ben Ryan', 'CS210', 29.5, 2, -4.95, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1045, 'Killian Byrne', 'CS210', 58.07, 3, 53.01, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1046, 'Darragh Doyle', 'CS210', 63.63, 3, -3.67, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1047, 'Michael Sheehan', 'CS210', 72.79, 3, 21.07, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1048, 'Aaron Murphy', 'CS210', 68.8, 3, 27.87, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1049, 'Alex Walsh', 'CS210', 70.49, 3, -49.39, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1050, 'Megan Murphy', 'CS210', 75.27, 3, -18.43, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1051, 'Michael Doyle', 'CS210', 56.04, 3, 5, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1052, 'Alex Doyle', 'CS210', 45.75, 2, 14.72, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1053, 'Killian Kelly', 'CS210', 47.5, 2, -25.05, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1054, 'Killian Quinn', 'CS210', 35.5, 2, 1.93, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1055, 'Aaliyah Sheehan', 'CS210', 57.78, 3, 34.87, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1056, 'Killian Walsh', 'CS210', 63.53, 3, -8.82, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1057, 'Aaliyah Smith', 'CS210', 62.76, 3, 25.31, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1058, 'Abdula Doyle', 'CS210', 71.79, 3, 5.04, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1059, 'Darragh Kelly', 'CS210', 79.38, 3, -27.37, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1060, 'Ben Moran', 'CS210', 56.41, 3, 5.42, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1061, 'Conor Boyle', 'CS210', 58.55, 3, -6.74, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1062, 'Ciara Boyle', 'CS210', 59.33, 3, -2.15, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1063, 'Aaliyah Moran', 'CS210', 72.68, 3, 22.36, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1064, 'Aaron Sheehan', 'CS210', 42.68, 2, -14.31, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1065, 'Abdula Kelly', 'CS210', 54.24, 2, -19.09, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1066, 'Ciara Doyle', 'CS210', 57.14, 3, -2.9, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1067, 'Ciara Ryan', 'CS210', 70.42, 3, 20.68, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1068, 'Kate Ryan', 'CS210', 74.83, 3, 21.59, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1069, 'Aaliyah Kennedy', 'CS210', 68.44, 3, 21.22, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1070, 'Leo Smith', 'CS210', 46.36, 2, -16.79, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1071, 'Ciara Doyle', 'CS210', 61.68, 3, -11.82, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1072, 'Darragh Boyle', 'CS210', 39.77, 2, -29.58, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1073, 'Killian Quinn', 'CS210', 59.38, 3, 3.26, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1074, 'Conor Boyle', 'CS210', 67.4, 3, -1.99, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1075, 'Ben Quinn', 'CS210', 42.33, 2, 45.56, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1076, 'Killian Moran', 'CS210', 82.61, 3, 18.42, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1077, 'Aaron Doyle', 'CS210', 51.48, 2, -16.18, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1078, 'Megan Doyle', 'CS210', 69.02, 3, 6.5, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1079, 'Kate Sheehan', 'CS210', 48.17, 2, -12.56, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1080, 'Darragh Boyle', 'CS210', 66.65, 3, 5.56, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1081, 'Kate Doyle', 'CS210', 58.79, 3, 1.73, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1082, 'Ben Ryan', 'CS210', 60.46, 3, 7.84, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1083, 'Kate Walsh', 'CS210', 54.79, 3, -1.63, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1084, 'Adam Sheehan', 'CS210', 69.99, 3, 30.12, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1085, 'Aaron Kennedy', 'CS210', 53.66, 2, 39.02, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1086, 'Conor Walsh', 'CS210', 49.56, 2, -41.23, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1087, 'Killian Doyle', 'CS210', 37.42, 2, -14.37, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1088, 'Killian Kelly', 'CS210', 57.09, 3, -37.68, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1089, 'Leo McCarthy', 'CS210', 81.44, 3, 21.76, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1090, 'Darragh Murphy', 'CS210', 83.79, 3, -2.5, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1091, 'Abdula Smith', 'CS210', 24.74, 1, 0, 2, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1092, 'Conor Ryan', 'CS210', 83.12, 3, 10.06, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1093, 'Adam Ryan', 'CS210', 67.12, 3, -45.03, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1094, 'Ciara Boyle', 'CS210', 60.61, 3, 4.71, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1095, 'Michael Smith', 'CS210', 59.11, 3, -7.77, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1096, 'Megan Byrne', 'CS210', 44.17, 2, 9.92, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1097, 'Abdula Sheehan', 'CS210', 74.52, 3, -27.75, 0, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1098, 'Adam Quinn', 'CS210', 42.49, 2, -10.89, 1, 0.13);
INSERT INTO students (student_id, student_name, module, average_score, assessments_completed, performance_trend, max_consecutive_misses, progress_in_semester) VALUES (1099, 'Conor Kelly', 'CS210', 60.16, 3, 17.18, 0, 0.13);
